name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: One-line script
      run: echo Hello, world!
    - name: MUlti-line script
      run: |
        echo One action
        echo Another action
